version: '3.7'
services:
  # WebServer config
  webserver:
    build: .
    volumes:
       - "./src:/var/www/html"
    #command: yum update
    ports:
     - "8680:80"
    depends_on:
     - db

  db:
    image: postgres:11
    volumes:
#      - ./db_data:/var/lib/postgresql/data
      - ./tmp:/tmp
    ports:
      - "54320:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
